/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/research/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_research_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rows
         * @description Every result of a strategy on one of our lists, judged, in the board's order.
         */
        get: operations["list_rows_api_research_lists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Asset Rows
         * @description Every strategy alone on an instrument, once a (strategy, instrument, timeframe).
         */
        get: operations["asset_rows_api_research_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result */
        get: operations["result_api_research_result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/curves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Curves */
        get: operations["curves_api_research_curves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Current */
        get: operations["run_current_api_runs_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Start */
        post: operations["run_start_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Stop */
        post: operations["run_stop_api_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Resume */
        post: operations["run_resume_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description hello on connecting; then results, judged, code, run and reset as they happen (server.live).
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alone */
        Alone: {
            /** Key */
            key: string;
            /** Sharpe */
            sharpe: number | null;
            /** Vs Bh */
            vs_bh: number | null;
            /** Beats Bh */
            beats_bh: boolean;
            /** Stale */
            stale: boolean;
        };
        /** AssetInfo */
        AssetInfo: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Market */
            market: string;
            /** Liquidity */
            liquidity: number | null;
        };
        /** AssetRow */
        AssetRow: {
            /** Key */
            key: string;
            /** Id */
            id: number;
            /** Strategy */
            strategy: string;
            /** List Id */
            list_id: string;
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1h" | "4h" | "1d";
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Months */
            months: number | null;
            /** Avg Monthly */
            avg_monthly: number | null;
            /** Cagr */
            cagr: number | null;
            /** Green */
            green: number | null;
            /** Max Dd */
            max_dd: number | null;
            /** At Target Dd */
            at_target_dd: number | null;
            /** At Target Dd Multiple */
            at_target_dd_multiple: number | null;
            /** At Target Dd 5Y */
            at_target_dd_5y: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** K Ratio */
            k_ratio: number | null;
            /** Trades */
            trades: number | null;
            /** Beats Bh */
            beats_bh: boolean;
            /** Vs Bh */
            vs_bh: number | null;
            /** Bh Cash */
            bh_cash: boolean;
            /** Bh Sharpe */
            bh_sharpe: number | null;
            /** Bh Max Dd */
            bh_max_dd: number | null;
            /** Bh K Ratio */
            bh_k_ratio: number | null;
            /** Bh At Target Dd */
            bh_at_target_dd: number | null;
            /** Bh At Target Dd Multiple */
            bh_at_target_dd_multiple: number | null;
            /** Targets */
            targets: boolean[];
            /** Targets Met */
            targets_met: number;
            robustness: components["schemas"]["Robustness"] | null;
            /** Loses */
            loses: string | null;
            /** Stale */
            stale: boolean;
            /** Instrument Id */
            instrument_id: string;
            /** Bh Avg Monthly */
            bh_avg_monthly: number | null;
            /** Params Now */
            params_now: {
                [key: string]: unknown;
            } | null;
            /** Held */
            held: boolean;
        };
        /** AssetRows */
        AssetRows: {
            /** Rows */
            rows: components["schemas"]["AssetRow"][];
        };
        /** BenchmarkFigures */
        BenchmarkFigures: {
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Months */
            months: number | null;
            /** Avg Monthly */
            avg_monthly: number | null;
            /** Median Monthly */
            median_monthly: number | null;
            /** Pct Green */
            pct_green: number | null;
            /** Pct Red */
            pct_red: number | null;
            /** Months Active */
            months_active: number | null;
            /** Pct Months Active */
            pct_months_active: number | null;
            /** Pct Green Active */
            pct_green_active: number | null;
            /** Pct Red Active */
            pct_red_active: number | null;
            /** Worst Month */
            worst_month: number | null;
            /** Best Month */
            best_month: number | null;
            /** Longest Red Streak */
            longest_red_streak: number | null;
            /** Cagr */
            cagr: number | null;
            /** Ann Vol */
            ann_vol: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Sortino */
            sortino: number | null;
            /** Max Dd */
            max_dd: number | null;
            /** Max Dd Days */
            max_dd_days: number | null;
            /** K Ratio */
            k_ratio: number | null;
            /** At Target Dd */
            at_target_dd: number | null;
            /** At Target Dd Multiple */
            at_target_dd_multiple: number | null;
            /** At Target Dd 5Y */
            at_target_dd_5y: number | null;
        };
        /** BenchmarkView */
        BenchmarkView: {
            /** Pts */
            pts: [
                number,
                number
            ][];
            months: components["schemas"]["Months"] | null;
            /** Growth */
            growth: number | null;
            figures: components["schemas"]["BenchmarkFigures"];
        };
        /** Candidate */
        Candidate: {
            /** Key */
            key: string;
            /** Strategy */
            strategy: string;
            /** Sharpe */
            sharpe: number | null;
            /** Windows */
            windows: number;
            /** Stale */
            stale: boolean;
        };
        /** Cell */
        Cell: {
            /** Key */
            key: string;
            /** List Id */
            list_id: string;
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1h" | "4h" | "1d";
            /** Sharpe */
            sharpe: number | null;
            /** Avg Monthly */
            avg_monthly: number | null;
            /** Cagr */
            cagr: number | null;
            /** Vs Bh */
            vs_bh: number | null;
            /** Beats Bh */
            beats_bh: boolean;
            /** Bh Cash */
            bh_cash: boolean;
            /** Targets Met */
            targets_met: number;
            /** Stale */
            stale: boolean;
        };
        /** CheckInfo */
        CheckInfo: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** CurveLine */
        CurveLine: {
            /** Pts */
            pts: [
                number,
                number
            ][];
            /** Benchmark */
            benchmark: [
                number,
                number
            ][] | null;
            /** Index */
            index: [
                number,
                number
            ][] | null;
            /** Index Name */
            index_name: string | null;
        };
        /** CurveView */
        CurveView: {
            /** Pts */
            pts: [
                number,
                number
            ][];
            /** Dd */
            dd: (number | null)[];
            months: components["schemas"]["Months"] | null;
            /** Growth */
            growth: number | null;
        };
        /** Curves */
        Curves: {
            /** Curves */
            curves: {
                [key: string]: components["schemas"]["CurveLine"];
            };
        };
        /** Elsewhere */
        Elsewhere: {
            /** Lists */
            lists: components["schemas"]["Cell"][];
            /** Alone */
            alone: components["schemas"]["Cell"][];
        };
        /** FailedJob */
        FailedJob: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "lists" | "single_assets";
            /** Strategy */
            strategy: string;
            /** List Id */
            list_id: string;
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1h" | "4h" | "1d";
            /** Attempts */
            attempts: number;
            /** Error */
            error: string | null;
        };
        /** Figures */
        Figures: {
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Months */
            months: number | null;
            /** Avg Monthly */
            avg_monthly: number | null;
            /** Median Monthly */
            median_monthly: number | null;
            /** Pct Green */
            pct_green: number | null;
            /** Pct Red */
            pct_red: number | null;
            /** Months Active */
            months_active: number | null;
            /** Pct Months Active */
            pct_months_active: number | null;
            /** Pct Green Active */
            pct_green_active: number | null;
            /** Pct Red Active */
            pct_red_active: number | null;
            /** Worst Month */
            worst_month: number | null;
            /** Best Month */
            best_month: number | null;
            /** Longest Red Streak */
            longest_red_streak: number | null;
            /** Cagr */
            cagr: number | null;
            /** Ann Vol */
            ann_vol: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Sortino */
            sortino: number | null;
            /** Max Dd */
            max_dd: number | null;
            /** Max Dd Days */
            max_dd_days: number | null;
            /** K Ratio */
            k_ratio: number | null;
            /** At Target Dd */
            at_target_dd: number | null;
            /** At Target Dd Multiple */
            at_target_dd_multiple: number | null;
            /** At Target Dd 5Y */
            at_target_dd_5y: number | null;
            /** N Trades */
            n_trades: number | null;
            /** Trades Per Month */
            trades_per_month: number | null;
            /** Win Rate */
            win_rate: number | null;
            /** Avg Trade */
            avg_trade: number | null;
            /** Median Trade Bars */
            median_trade_bars: number | null;
            /** Time In Market */
            time_in_market: number | null;
            /** Avg Gross */
            avg_gross: number | null;
            /** Avg Win */
            avg_win: number | null;
            /** Avg Loss */
            avg_loss: number | null;
            /** Profit Factor */
            profit_factor: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexView */
        IndexView: {
            /** Pts */
            pts: [
                number,
                number
            ][];
            months: components["schemas"]["Months"] | null;
            /** Growth */
            growth: number | null;
            figures: components["schemas"]["BenchmarkFigures"];
            /** Name */
            name: string;
        };
        /** ListInfo */
        ListInfo: {
            /** Id */
            id: string;
            /** Market */
            market: string;
            /** Label */
            label: string;
            /** Title */
            title: string;
            /** Research */
            research: boolean;
            /** Per Instrument */
            per_instrument: boolean;
            /** Venue */
            venue: string | null;
            /** Costs */
            costs: string | null;
            size: components["schemas"]["ListSize"] | null;
        };
        /** ListRow */
        ListRow: {
            /** Key */
            key: string;
            /** Id */
            id: number;
            /** Strategy */
            strategy: string;
            /** List Id */
            list_id: string;
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1h" | "4h" | "1d";
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Months */
            months: number | null;
            /** Avg Monthly */
            avg_monthly: number | null;
            /** Cagr */
            cagr: number | null;
            /** Green */
            green: number | null;
            /** Max Dd */
            max_dd: number | null;
            /** At Target Dd */
            at_target_dd: number | null;
            /** At Target Dd Multiple */
            at_target_dd_multiple: number | null;
            /** At Target Dd 5Y */
            at_target_dd_5y: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** K Ratio */
            k_ratio: number | null;
            /** Trades */
            trades: number | null;
            /** Beats Bh */
            beats_bh: boolean;
            /** Vs Bh */
            vs_bh: number | null;
            /** Bh Cash */
            bh_cash: boolean;
            /** Bh Sharpe */
            bh_sharpe: number | null;
            /** Bh Max Dd */
            bh_max_dd: number | null;
            /** Bh K Ratio */
            bh_k_ratio: number | null;
            /** Bh At Target Dd */
            bh_at_target_dd: number | null;
            /** Bh At Target Dd Multiple */
            bh_at_target_dd_multiple: number | null;
            /** Targets */
            targets: boolean[];
            /** Targets Met */
            targets_met: number;
            robustness: components["schemas"]["Robustness"] | null;
            /** Loses */
            loses: string | null;
            /** Stale */
            stale: boolean;
            /** Worst Month */
            worst_month: number | null;
            /** Evaluated At */
            evaluated_at: string;
        };
        /** ListRows */
        ListRows: {
            /** Rows */
            rows: components["schemas"]["ListRow"][];
        };
        /** ListSize */
        ListSize: {
            /** Fixed */
            fixed: number | null;
            /** Trading */
            trading: number | null;
            /** Held */
            held: number | null;
            /** Ever */
            ever: number | null;
        };
        /** Meta */
        Meta: {
            targets: components["schemas"]["Targets"];
            /** Capital */
            capital: number;
            /** Min Trades */
            min_trades: number;
            /** Markets */
            markets: string[];
            /** Lists */
            lists: components["schemas"]["ListInfo"][];
            /** Checks */
            checks: components["schemas"]["CheckInfo"][];
            /** Assets */
            assets: components["schemas"]["AssetInfo"][];
            strategies: components["schemas"]["StrategyNames"];
            tries: components["schemas"]["TriesInfo"] | null;
            /** Updated At */
            updated_at: string | null;
            stale: components["schemas"]["StaleCounts"];
        };
        /** Months */
        Months: {
            /** First */
            first: string;
            /** V */
            v: (number | null)[];
        };
        /** NameView */
        NameView: {
            /** Instrument Id */
            instrument_id: string;
            /** Label */
            label: string;
            /** Trades */
            trades: number;
            /** Won */
            won: number | null;
            /** Compounded */
            compounded: number | null;
            alone: components["schemas"]["Alone"] | null;
        };
        /** Refusal */
        Refusal: {
            /** Message */
            message: string;
            /** Confirm */
            confirm: boolean;
        };
        /** ResultView */
        ResultView: {
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "list" | "asset" | "pick";
            /** Row */
            row: components["schemas"]["ListRow"] | components["schemas"]["AssetRow"];
            /** Description */
            description: string;
            /** Notes */
            notes: string[];
            /** Fill */
            fill: string | null;
            /** Evaluated At */
            evaluated_at: string;
            figures: components["schemas"]["Figures"];
            curve: components["schemas"]["CurveView"];
            benchmark: components["schemas"]["BenchmarkView"] | null;
            index: components["schemas"]["IndexView"] | null;
            windows: components["schemas"]["WindowsView"] | null;
            /** Params */
            params: {
                [key: string]: unknown;
            } | null;
            /** Grid */
            grid: {
                [key: string]: unknown[];
            } | null;
            /** Params Now */
            params_now: {
                [key: string]: unknown;
            } | null;
            /** Names */
            names: components["schemas"]["NameView"][];
            elsewhere: components["schemas"]["Elsewhere"];
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
            /** Beyond Luck */
            beyond_luck: number | null;
        };
        /** Robustness */
        Robustness: {
            /** Passed */
            passed: number;
            /** Applicable */
            applicable: number;
            /** Not Computed */
            not_computed: number;
            /** Checks */
            checks: [
                string,
                string,
                string,
                "passed" | "failed" | "too_short" | "not_applicable" | "not_computed"
            ][];
        };
        /** RunAccepted */
        RunAccepted: {
            /** Id */
            id: number;
        };
        /** RunCurrent */
        RunCurrent: {
            run: components["schemas"]["RunView"] | null;
        };
        /** RunOnly */
        RunOnly: {
            /** Strategies */
            strategies?: string[] | null;
            /** Lists */
            lists?: string[] | null;
            /** Timeframes */
            timeframes?: ("1h" | "4h" | "1d")[] | null;
        };
        /** RunResume */
        RunResume: {
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
        };
        /** RunStart */
        RunStart: {
            /**
             * Single Assets
             * @default false
             */
            single_assets: boolean;
            /**
             * Everything
             * @default false
             */
            everything: boolean;
            only?: components["schemas"]["RunOnly"] | null;
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
        };
        /** RunView */
        RunView: {
            /** Id */
            id: number;
            /**
             * State
             * @enum {string}
             */
            state: "starting" | "running" | "stopping" | "stopped" | "interrupted" | "done";
            /** Stage */
            stage: ("lists" | "single_assets" | "picks" | "summaries") | null;
            /** Active */
            active: boolean;
            /**
             * Requested By
             * @enum {string}
             */
            requested_by: "ui" | "cli";
            /** Requested At */
            requested_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Single Assets */
            single_assets: boolean;
            /** Everything */
            everything: boolean;
            /** Narrowed To */
            narrowed_to: string | null;
            /** Resumed */
            resumed: number;
            /** Code Changed */
            code_changed: boolean;
            /** Stages */
            stages: components["schemas"]["StageProgress"][];
            /** Running */
            running: components["schemas"]["RunningJob"][];
            /** Failed */
            failed: components["schemas"]["FailedJob"][];
            /** Eta Seconds */
            eta_seconds: number | null;
            /** Cpu Seconds */
            cpu_seconds: number | null;
            /** Error */
            error: string | null;
            /** Log Path */
            log_path: string | null;
        };
        /** RunningJob */
        RunningJob: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "lists" | "single_assets";
            /** Strategy */
            strategy: string;
            /** List Id */
            list_id: string;
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1h" | "4h" | "1d";
            /** Started At */
            started_at: string | null;
            /** Expected Seconds */
            expected_seconds: number;
        };
        /** StageProgress */
        StageProgress: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "lists" | "single_assets";
            /** Total */
            total: number;
            /** Done */
            done: number;
            /** Failed */
            failed: number;
            /** Skipped */
            skipped: number;
            /** Stopped */
            stopped: number;
            /** Queued */
            queued: number;
            /** Running */
            running: number;
        };
        /** StaleCounts */
        StaleCounts: {
            /** Lists */
            lists: number;
            /** Assets */
            assets: number;
        };
        /** StrategyNames */
        StrategyNames: {
            /** Lists */
            lists: string[];
            /** Assets */
            assets: string[];
        };
        /** Targets */
        Targets: {
            /** Avg Monthly */
            avg_monthly: number;
            /** Avg Monthly Stretch */
            avg_monthly_stretch: number;
            /** Pct Green */
            pct_green: number;
            /** Pct Green Stretch */
            pct_green_stretch: number;
            /** Max Dd */
            max_dd: number;
            /** Sharpe */
            sharpe: number;
        };
        /** TriesInfo */
        TriesInfo: {
            /** Saved */
            saved: number;
            /** Independent */
            independent: number;
            /** Best 95 */
            best_95: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WindowsView */
        WindowsView: {
            /** Sets */
            sets: {
                [key: string]: unknown;
            }[];
            /** End */
            end: string;
            /** Train */
            train: number;
            /** W */
            w: [
                string,
                number
            ][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_research_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    list_rows_api_research_lists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRows"];
                };
            };
        };
    };
    asset_rows_api_research_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRows"];
                };
            };
        };
    };
    result_api_research_result_get: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    curves_api_research_curves_get: {
        parameters: {
            query: {
                keys: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Curves"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_current_api_runs_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCurrent"];
                };
            };
        };
    };
    run_start_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stop_api_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_resume_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunResume"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
}
